#ifndef __EEPROM_H
#define __EEPROM_H

#include "stm32f10x.h"


typedef enum _EEPROMAddressType
{
E2ROM_ZOOM_SPEED_ADDR=10,
E2ROM_ZOOM_DATA_ADDR=E2ROM_ZOOM_SPEED_ADDR+1,
E2ROM_DIG_ZOOM_ADDR=E2ROM_ZOOM_DATA_ADDR+1,
E2ROM_OSD_ADDR=E2ROM_DIG_ZOOM_ADDR+1,
E2ROM_ZOOM_DISPLAY_ADDR=E2ROM_OSD_ADDR+1,  //13
E2ROM_FOCUS_MODE_ADDR=E2ROM_ZOOM_DISPLAY_ADDR+1,
E2ROM_AF_SENS_ADDR=E2ROM_FOCUS_MODE_ADDR+1,
E2ROM_FOCUS_LIGHT_ADDR=E2ROM_AF_SENS_ADDR+1,
E2ROM_NEAR_LIMIT_ADDR=E2ROM_FOCUS_LIGHT_ADDR+1,  //17

E2ROM_AE_MODE_ADDR=E2ROM_NEAR_LIMIT_ADDR+1,	
E2ROM_SHUTTER_ADDR=E2ROM_AE_MODE_ADDR+1,
E2ROM_IRIS_ADDR=E2ROM_SHUTTER_ADDR+1,
E2ROM_GAIN_ADDR=E2ROM_IRIS_ADDR+1,
E2ROM_BRI_ADDR=E2ROM_GAIN_ADDR+1,
E2ROM_SLOW_AE_ADDR=E2ROM_BRI_ADDR+1, 
E2ROM_SLOW_SHUTTER_ADDR=E2ROM_SLOW_AE_ADDR+1, //24

E2ROM_WB_MODE_ADDR=E2ROM_SLOW_SHUTTER_ADDR+1,
E2ROM_RED_GAIN_ADDR=E2ROM_WB_MODE_ADDR+1,
E2ROM_BLUE_GAIN_ADDR=E2ROM_RED_GAIN_ADDR+1,  //27
	
E2ROM_BLC_ADDR=E2ROM_BLUE_GAIN_ADDR+1,
E2ROM_WDR_ADDR=E2ROM_BLC_ADDR+1,
E2ROM_NR_LEVEL_ADDR=E2ROM_WDR_ADDR+1,
E2ROM_STABILIZER_ADDR=E2ROM_NR_LEVEL_ADDR+1,
E2ROM_DEFOG_MODE_ADDR=E2ROM_STABILIZER_ADDR+1, //32

E2ROM_ZONE_ADDR=E2ROM_DEFOG_MODE_ADDR+1,
E2ROM_PRIVACY_DATA_ADDR=E2ROM_ZONE_ADDR+1,    //34  ÓÃ20¸ö×Ö½Ú´æ´¢

E2ROM_APERTURE_ADDR=E2ROM_PRIVACY_DATA_ADDR+20, //54
E2ROM_COLOR_GAIN_ADDR=E2ROM_APERTURE_ADDR+1,
E2ROM_COLOR_HUM_ADDR=E2ROM_COLOR_GAIN_ADDR+1,
E2ROM_CHROMA_SUPPRESS_ADDR=E2ROM_COLOR_HUM_ADDR+1,
E2ROM_GAMMA_ADDR=E2ROM_CHROMA_SUPPRESS_ADDR+1,
E2ROM_MIRROR_ADDR=E2ROM_GAMMA_ADDR+1,
E2ROM_FLIP_ADDR=E2ROM_MIRROR_ADDR+1,
E2ROM_FREEZE_ADDR=E2ROM_FLIP_ADDR+1,
E2ROM_PIC_EFFECT_ADDR=E2ROM_FREEZE_ADDR+1, //62

E2ROM_HI_RESOLUTION_ADDR=E2ROM_PIC_EFFECT_ADDR+1,
E2ROM_HI_SENSITIVITY_ADDR=E2ROM_HI_RESOLUTION_ADDR+1, //64

E2ROM_FORMAT_ADDR=E2ROM_HI_SENSITIVITY_ADDR+1,
E2ROM_LR_HANT_ADDR=E2ROM_FORMAT_ADDR+1,
E2ROM_BAUDRATE_ADDR=E2ROM_LR_HANT_ADDR+1,
E2ROM_ADDRESS_ADDR=E2ROM_BAUDRATE_ADDR+1,
E2ROM_AUX_ADDR=E2ROM_ADDRESS_ADDR+1,

E2ROM_SCENE_NUM_ADDR=E2ROM_AUX_ADDR+1,
E2ROM_SCENE_DATA_ADDR=E2ROM_SCENE_NUM_ADDR+1,

E2ROM_DEF_LAST_ADDR=E2ROM_SCENE_DATA_ADDR+6,


/***********************************************
				×Ô¶¨Òå³¡¾°£±µÄ²ÎÊý±
***********************************************/
E2ROM_ZOOM_SPEED_SCENE1_ADDR=E2ROM_SCENE_DATA_ADDR+6, //77
E2ROM_ZOOM_DATA_SCENE1_ADDR=E2ROM_ZOOM_SPEED_SCENE1_ADDR+1,
E2ROM_FOCUS_MODE_SCENE1_ADDR=E2ROM_ZOOM_DATA_SCENE1_ADDR+1,
E2ROM_AF_SENS_SCENE1_ADDR=E2ROM_FOCUS_MODE_SCENE1_ADDR+1,
E2ROM_FOCUS_LIGHT_SCENE1_ADDR=E2ROM_AF_SENS_SCENE1_ADDR+1,
E2ROM_NEAR_LIMIT_SCENE1_ADDR=E2ROM_FOCUS_LIGHT_SCENE1_ADDR+1,  //17

E2ROM_AE_MODE_SCENE1_ADDR=E2ROM_NEAR_LIMIT_SCENE1_ADDR+1,	
E2ROM_SHUTTER_SCENE1_ADDR=E2ROM_AE_MODE_SCENE1_ADDR+1,
E2ROM_IRIS_SCENE1_ADDR=E2ROM_AE_MODE_SCENE1_ADDR+1,
E2ROM_GAIN_SCENE1_ADDR=E2ROM_IRIS_SCENE1_ADDR+1,
E2ROM_BRI_SCENE1_ADDR=E2ROM_GAIN_SCENE1_ADDR+1,
E2ROM_SLOW_AE_SCENE1_ADDR=E2ROM_BRI_SCENE1_ADDR+1, 
E2ROM_SLOW_SHUTTER_SCENE1_ADDR=E2ROM_SLOW_AE_SCENE1_ADDR+1, //24

E2ROM_WB_MODE_SCENE1_ADDR=E2ROM_SLOW_SHUTTER_SCENE1_ADDR+1,
E2ROM_RED_GAIN_SCENE1_ADDR=E2ROM_WB_MODE_SCENE1_ADDR+1,
E2ROM_BLUE_GAIN_SCENE1_ADDR=E2ROM_RED_GAIN_SCENE1_ADDR+1,  //27
	
E2ROM_BLC_SCENE1_ADDR=E2ROM_BLUE_GAIN_SCENE1_ADDR+1,
E2ROM_WDR_SCENE1_ADDR=E2ROM_BLC_SCENE1_ADDR+1,
E2ROM_NR_LEVEL_SCENE1_ADDR=E2ROM_WDR_SCENE1_ADDR+1,
E2ROM_STABILIZER_SCENE1_ADDR=E2ROM_NR_LEVEL_SCENE1_ADDR+1,
E2ROM_DEFOG_MODE_SCENE1_ADDR=E2ROM_STABILIZER_SCENE1_ADDR+1, //32

E2ROM_ZONE_SCENE1_ADDR=E2ROM_DEFOG_MODE_SCENE1_ADDR+1,
E2ROM_PRIVACY_DATA_SCENE1_ADDR=E2ROM_ZONE_SCENE1_ADDR+1,    //34  ÓÃ20¸ö×Ö½Ú´æ´¢

E2ROM_APERTURE_SCENE1_ADDR=E2ROM_PRIVACY_DATA_SCENE1_ADDR+20, //54
E2ROM_COLOR_GAIN_SCENE1_ADDR=E2ROM_APERTURE_SCENE1_ADDR+1,
E2ROM_COLOR_HUM_SCENE1_ADDR=E2ROM_COLOR_GAIN_SCENE1_ADDR+1,
E2ROM_CHROMA_SUPPRESS_SCENE1_ADDR=E2ROM_COLOR_HUM_SCENE1_ADDR+1,
E2ROM_GAMMA_SCENE1_ADDR=E2ROM_CHROMA_SUPPRESS_SCENE1_ADDR+1,
E2ROM_MIRROR_SCENE1_ADDR=E2ROM_GAMMA_SCENE1_ADDR+1,
E2ROM_FLIP_SCENE1_ADDR=E2ROM_MIRROR_SCENE1_ADDR+1,
E2ROM_FREEZE_SCENE1_ADDR=E2ROM_FLIP_SCENE1_ADDR+1,
E2ROM_PIC_EFFECT_SCENE1_ADDR=E2ROM_FREEZE_SCENE1_ADDR+1, //62

E2ROM_HI_RESOLUTION_SCENE1_ADDR=E2ROM_PIC_EFFECT_SCENE1_ADDR+1,
E2ROM_HI_SENSITIVITY_SCENE1_ADDR=E2ROM_HI_RESOLUTION_SCENE1_ADDR+1, //64

E2ROM_FORMAT_SCENE1_ADDR=E2ROM_HI_SENSITIVITY_SCENE1_ADDR+1,

E2ROM_SCENE1_LAST_ADDR=E2ROM_FORMAT_SCENE1_ADDR+1,

/***********************************************
				×Ô¶¨Òå³¡¾°£²µÄ²ÎÊý±
***********************************************/

E2ROM_ZOOM_SPEED_SCENE2_ADDR=E2ROM_FORMAT_SCENE1_ADDR+1, //77
E2ROM_ZOOM_DATA_SCENE2_ADDR=E2ROM_ZOOM_SPEED_SCENE2_ADDR+1,
E2ROM_FOCUS_MODE_SCENE2_ADDR=E2ROM_ZOOM_DATA_SCENE2_ADDR+1,
E2ROM_AF_SENS_SCENE2_ADDR=E2ROM_FOCUS_MODE_SCENE2_ADDR+1,
E2ROM_FOCUS_LIGHT_SCENE2_ADDR=E2ROM_AF_SENS_SCENE2_ADDR+1,
E2ROM_NEAR_LIMIT_SCENE2_ADDR=E2ROM_FOCUS_LIGHT_SCENE2_ADDR+1,  //17

E2ROM_AE_MODE_SCENE2_ADDR=E2ROM_NEAR_LIMIT_SCENE2_ADDR+1,	
E2ROM_SHUTTER_SCENE2_ADDR=E2ROM_AE_MODE_SCENE2_ADDR+1,
E2ROM_IRIS_SCENE2_ADDR=E2ROM_AE_MODE_SCENE2_ADDR+1,
E2ROM_GAIN_SCENE2_ADDR=E2ROM_IRIS_SCENE2_ADDR+1,
E2ROM_BRI_SCENE2_ADDR=E2ROM_GAIN_SCENE2_ADDR+1,
E2ROM_SLOW_AE_SCENE2_ADDR=E2ROM_BRI_SCENE2_ADDR+1, 
E2ROM_SLOW_SHUTTER_SCENE2_ADDR=E2ROM_SLOW_AE_SCENE2_ADDR+1, //24

E2ROM_WB_MODE_SCENE2_ADDR=E2ROM_SLOW_SHUTTER_SCENE2_ADDR+1,
E2ROM_RED_GAIN_SCENE2_ADDR=E2ROM_WB_MODE_SCENE2_ADDR+1,
E2ROM_BLUE_GAIN_SCENE2_ADDR=E2ROM_RED_GAIN_SCENE2_ADDR+1,  //27
	
E2ROM_BLC_SCENE2_ADDR=E2ROM_BLUE_GAIN_SCENE2_ADDR+1,
E2ROM_WDR_SCENE2_ADDR=E2ROM_BLC_SCENE2_ADDR+1,
E2ROM_NR_LEVEL_SCENE2_ADDR=E2ROM_WDR_SCENE2_ADDR+1,
E2ROM_STABILIZER_SCENE2_ADDR=E2ROM_NR_LEVEL_SCENE2_ADDR+1,
E2ROM_DEFOG_MODE_SCENE2_ADDR=E2ROM_STABILIZER_SCENE2_ADDR+1, //32

E2ROM_ZONE_SCENE2_ADDR=E2ROM_DEFOG_MODE_SCENE2_ADDR+1,
E2ROM_PRIVACY_DATA_SCENE2_ADDR=E2ROM_ZONE_SCENE2_ADDR+1,    //34  ÓÃ20¸ö×Ö½Ú´æ´¢

E2ROM_APERTURE_SCENE2_ADDR=E2ROM_PRIVACY_DATA_SCENE2_ADDR+20, //54
E2ROM_COLOR_GAIN_SCENE2_ADDR=E2ROM_APERTURE_SCENE2_ADDR+1,
E2ROM_COLOR_HUM_SCENE2_ADDR=E2ROM_COLOR_GAIN_SCENE2_ADDR+1,
E2ROM_CHROMA_SUPPRESS_SCENE2_ADDR=E2ROM_COLOR_HUM_SCENE2_ADDR+1,
E2ROM_GAMMA_SCENE2_ADDR=E2ROM_CHROMA_SUPPRESS_SCENE2_ADDR+1,
E2ROM_MIRROR_SCENE2_ADDR=E2ROM_GAMMA_SCENE2_ADDR+1,
E2ROM_FLIP_SCENE2_ADDR=E2ROM_MIRROR_SCENE2_ADDR+1,
E2ROM_FREEZE_SCENE2_ADDR=E2ROM_FLIP_SCENE2_ADDR+1,
E2ROM_PIC_EFFECT_SCENE2_ADDR=E2ROM_FREEZE_SCENE2_ADDR+1, //62

E2ROM_HI_RESOLUTION_SCENE2_ADDR=E2ROM_PIC_EFFECT_SCENE2_ADDR+1,
E2ROM_HI_SENSITIVITY_SCENE2_ADDR=E2ROM_HI_RESOLUTION_SCENE2_ADDR+1, //64

E2ROM_FORMAT_SCENE2_ADDR=E2ROM_HI_SENSITIVITY_SCENE2_ADDR+1,

E2ROM_SCENE2_LAST_ADDR=E2ROM_FORMAT_SCENE2_ADDR+1,


/***********************************************
				×Ô¶¨Òå³¡¾°3µÄ²ÎÊý±
***********************************************/

E2ROM_ZOOM_SPEED_SCENE3_ADDR=E2ROM_FORMAT_SCENE2_ADDR+1, //77
E2ROM_ZOOM_DATA_SCENE3_ADDR=E2ROM_ZOOM_SPEED_SCENE3_ADDR+1,
E2ROM_FOCUS_MODE_SCENE3_ADDR=E2ROM_ZOOM_DATA_SCENE3_ADDR+1,
E2ROM_AF_SENS_SCENE3_ADDR=E2ROM_FOCUS_MODE_SCENE3_ADDR+1,
E2ROM_FOCUS_LIGHT_SCENE3_ADDR=E2ROM_AF_SENS_SCENE3_ADDR+1,
E2ROM_NEAR_LIMIT_SCENE3_ADDR=E2ROM_FOCUS_LIGHT_SCENE3_ADDR+1,  //17

E2ROM_AE_MODE_SCENE3_ADDR=E2ROM_NEAR_LIMIT_SCENE3_ADDR+1,	
E2ROM_SHUTTER_SCENE3_ADDR=E2ROM_AE_MODE_SCENE3_ADDR+1,
E2ROM_IRIS_SCENE3_ADDR=E2ROM_AE_MODE_SCENE3_ADDR+1,
E2ROM_GAIN_SCENE3_ADDR=E2ROM_IRIS_SCENE3_ADDR+1,
E2ROM_BRI_SCENE3_ADDR=E2ROM_GAIN_SCENE3_ADDR+1,
E2ROM_SLOW_AE_SCENE3_ADDR=E2ROM_BRI_SCENE3_ADDR+1, 
E2ROM_SLOW_SHUTTER_SCENE3_ADDR=E2ROM_SLOW_AE_SCENE3_ADDR+1, //24

E2ROM_WB_MODE_SCENE3_ADDR=E2ROM_SLOW_SHUTTER_SCENE3_ADDR+1,
E2ROM_RED_GAIN_SCENE3_ADDR=E2ROM_WB_MODE_SCENE3_ADDR+1,
E2ROM_BLUE_GAIN_SCENE3_ADDR=E2ROM_RED_GAIN_SCENE3_ADDR+1,  //27
	
E2ROM_BLC_SCENE3_ADDR=E2ROM_BLUE_GAIN_SCENE3_ADDR+1,
E2ROM_WDR_SCENE3_ADDR=E2ROM_BLC_SCENE3_ADDR+1,
E2ROM_NR_LEVEL_SCENE3_ADDR=E2ROM_WDR_SCENE3_ADDR+1,
E2ROM_STABILIZER_SCENE3_ADDR=E2ROM_NR_LEVEL_SCENE3_ADDR+1,
E2ROM_DEFOG_MODE_SCENE3_ADDR=E2ROM_STABILIZER_SCENE3_ADDR+1, //32

E2ROM_ZONE_SCENE3_ADDR=E2ROM_DEFOG_MODE_SCENE3_ADDR+1,
E2ROM_PRIVACY_DATA_SCENE3_ADDR=E2ROM_ZONE_SCENE3_ADDR+1,    //34  ÓÃ20¸ö×Ö½Ú´æ´¢

E2ROM_APERTURE_SCENE3_ADDR=E2ROM_PRIVACY_DATA_SCENE3_ADDR+20, //54
E2ROM_COLOR_GAIN_SCENE3_ADDR=E2ROM_APERTURE_SCENE3_ADDR+1,
E2ROM_COLOR_HUM_SCENE3_ADDR=E2ROM_COLOR_GAIN_SCENE3_ADDR+1,
E2ROM_CHROMA_SUPPRESS_SCENE3_ADDR=E2ROM_COLOR_HUM_SCENE3_ADDR+1,
E2ROM_GAMMA_SCENE3_ADDR=E2ROM_CHROMA_SUPPRESS_SCENE3_ADDR+1,
E2ROM_MIRROR_SCENE3_ADDR=E2ROM_GAMMA_SCENE3_ADDR+1,
E2ROM_FLIP_SCENE3_ADDR=E2ROM_MIRROR_SCENE3_ADDR+1,
E2ROM_FREEZE_SCENE3_ADDR=E2ROM_FLIP_SCENE3_ADDR+1,
E2ROM_PIC_EFFECT_SCENE3_ADDR=E2ROM_FREEZE_SCENE3_ADDR+1, //62

E2ROM_HI_RESOLUTION_SCENE3_ADDR=E2ROM_PIC_EFFECT_SCENE3_ADDR+1,
E2ROM_HI_SENSITIVITY_SCENE3_ADDR=E2ROM_HI_RESOLUTION_SCENE3_ADDR+1, //64

E2ROM_FORMAT_SCENE3_ADDR=E2ROM_HI_SENSITIVITY_SCENE3_ADDR+1,
E2ROM_SCENE3_LAST_ADDR=E2ROM_FORMAT_SCENE3_ADDR+1,

E2ROM_LAST_ADDR=E2ROM_HI_SENSITIVITY_SCENE3_ADDR+1,
	                         
}EEPROMAddressType;




/* Exported macro ------------------------------------------------------------*/ 
#define ADDR_24CXX        0xA0  
#define SCLH         GPIOB->BSRR = GPIO_Pin_10 
#define SCLL         GPIOB->BRR  = GPIO_Pin_10      
#define SDAH         GPIOB->BSRR = GPIO_Pin_11 
#define SDAL         GPIOB->BRR  = GPIO_Pin_11 
#define SCLread      GPIOB->IDR  & GPIO_Pin_10 
#define SDAread      GPIOB->IDR  & GPIO_Pin_11 

void I2C_EE_Init(void);
u8 I2C_EE_BufferWrite(u8 *psrc_data,u8 adr,u8 nbyte);
u8 I2C_EE_BufferRead(u8 *pdin_data,u8 adr,u8 nbyte);
uint8_t TWI_ReadByte( u8 * pBuffer ,u32 ReadAddress);
uint8_t TWI_WriteByte(uint8_t SendByte, uint32_t WriteAddress);
u8 CheckEEPRom(void);

#endif
